export const GAME_FILTERS = {
	ALL: 'all',
	NOTSTARTED: 'notstarted',
	UNFINISHED: 'unfinished'
}
export const NFL_TEAM_NAMES = [
	'49ers',
	'Bears',
	'Bengals',
	'Bills',
	'Broncos',
	'Browns',
	'Buccaneers',
	'Cardinals',
	'Chargers',
	'Chiefs',
	'Colts',
	'Commanders',
	'Cowboys',
	'Dolphins',
	'Eagles',
	'Falcons',
	'Giants',
	'Jaguars',
	'Jets',
	'Lions',
	'Packers',
	'Panthers',
	'Patriots',
	'Raiders',
	'Rams',
	'Ravens',
	'Saints',
	'Seahawks',
	'Steelers',
	'Texans',
	'Titans',
	'Vikings'
]

export const NFL_TEAMS = [
	{ name: '49ers', abbreviation: 'SF' },
	{ name: 'Bears', abbreviation: 'CHI' },
	{ name: 'Bengals', abbreviation: 'CIN' },
	{ name: 'Bills', abbreviation: 'BUF' },
	{ name: 'Broncos', abbreviation: 'DEN' },
	{ name: 'Browns', abbreviation: 'CLE' },
	{ name: 'Buccaneers', abbreviation: 'TB' },
	{ name: 'Cardinals', abbreviation: 'AZ' },
	{ name: 'Chargers', abbreviation: 'LAC' },
	{ name: 'Chiefs', abbreviation: 'KC' },
	{ name: 'Colts', abbreviation: 'IND' },
	{ name: 'Commanders', abbreviation: 'WAS' },
	{ name: 'Cowboys', abbreviation: 'DAL' },
	{ name: 'Dolphins', abbreviation: 'MIA' },
	{ name: 'Eagles', abbreviation: 'PHI' },
	{ name: 'Falcons', abbreviation: 'ATL' },
	{ name: 'Giants', abbreviation: 'NYG' },
	{ name: 'Jaguars', abbreviation: 'JAC' },
	{ name: 'Jets', abbreviation: 'NYJ' },
	{ name: 'Lions', abbreviation: 'DET' },
	{ name: 'Packers', abbreviation: 'GB' },
	{ name: 'Panthers', abbreviation: 'CAR' },
	{ name: 'Patriots', abbreviation: 'NE' },
	{ name: 'Raiders', abbreviation: 'LV' },
	{ name: 'Rams', abbreviation: 'LAR' },
	{ name: 'Ravens', abbreviation: 'BAL' },
	{ name: 'Saints', abbreviation: 'NO' },
	{ name: 'Seahawks', abbreviation: 'SEA' },
	{ name: 'Steelers', abbreviation: 'PIT' },
	{ name: 'Texans', abbreviation: 'HOU' },
	{ name: 'Titans', abbreviation: 'TEN' },
	{ name: 'Vikings', abbreviation: 'MIN' }
]
