import {
	defaultNfeloPasteInput1,
	defaultNfeloPasteInput2,
	defaultNfeloPasteInput3,
	defaultNfeloPasteInput4,
	defaultNfeloPasteInput5,
	defaultNfeloPasteInput6,
	defaultNfeloPasteInput7,
	defaultNfeloPasteInput8,
	defaultNfeloPasteInput9,
	defaultNfeloPasteInput10,
	defaultNfeloPasteInput11,
	defaultNfeloPasteInput12,
	defaultNfeloPasteInput13,
	defaultNfeloPasteInput14,
	defaultNfeloPasteInput15,
	defaultNfeloPasteInput16,
	defaultNfeloPasteInput17,
	defaultNfeloPasteInput18
} from '~/utils/defaults/defaultNfeloPastesWeeks/weeks'

export const defaultNfeloPasteInputs = [
	defaultNfeloPasteInput1,
	defaultNfeloPasteInput2,
	defaultNfeloPasteInput3,
	defaultNfeloPasteInput4,
	defaultNfeloPasteInput5,
	defaultNfeloPasteInput6,
	defaultNfeloPasteInput7,
	defaultNfeloPasteInput8,
	defaultNfeloPasteInput9,
	defaultNfeloPasteInput10,
	defaultNfeloPasteInput11,
	defaultNfeloPasteInput12,
	defaultNfeloPasteInput13,
	defaultNfeloPasteInput14,
	defaultNfeloPasteInput15,
	defaultNfeloPasteInput16,
	defaultNfeloPasteInput17,
	defaultNfeloPasteInput18
]
